### ISSUE TITLE
PNI does not read h5py bool datesets

### ISSUE THREAD

**Issue by jkotan** [pni-libraries/python-pni#21]
Hi Eugen,

I've just noticed that PNI does not read h5py bool datesets, i.e.

    import h5py
    from pni.io.nx.h5 import open_file

    f = h5py.File("booltest.h5", "w")
    ds = f.create_dataset("bool_flag", [1], "bool")
    ds[...] = True
    f.close()

    f = open_file("booltest.h5", readonly=True)
    r = f.root()
    bf = r.open("bool_flag")

    dt = bf[...]

    print bf.dtype

gives

    Traceback (most recent call last):
      File "booltool.py", line 14, in <module>
        dt = bf[...]
    TypeError: Exception: type_error

    Description:
    HDF5 type is unkown!

    Exception thrown by:
    /tmp/buildd/libpniio-1.1.0/src/nx/h5/h5datatype.cpp	253	pni::core::type_id_t pni::io::nx::h5::type_id(const pni::io::nx::h5::h5datatype&)

That's probably because bools are integers for PNI while for h5py there are enums.

Cheers,
Jan

**Comment by jkotan** [comment]
with the new API (v1.2.3) the bug can be reproduced by

    import h5py
    from pninexus import h5cpp
    from pninexus import nexus


    f = h5py.File("booltest.h5", "w")
    ds = f.create_dataset("bool_flag", [1], "bool")
    ds[...] = True
    f.close()

    flag = h5cpp.file.AccessFlags.READONLY
    fl = h5cpp.file.open("booltest.h5", flag)

    bf = nexus.get_objects(
        fl.root(),
        nexus.Path(h5cpp.Path("/bool_flag")))[0]
    bf.read()
    fl.close()

where we get

    Traceback (most recent call last):
      File "h5pybool.py", line 17, in <module>
        bf.read()
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pninexus/h5cpp/node/__init__.py", line 337, in dataset_read
        data = numpy.empty(shape, dtype=datatype.to_numpy(memory_type))
      File "/home/jkotan/testinst/lib/python2.7/site-packages/pninexus/h5cpp/datatype/__init__.py", line 119, in to_numpy
        raise ValueError("Unsupported HDF5 datatype!")
    ValueError: Unsupported HDF5 datatype!

It is somehow related to https://github.com/pni-libraries/python-pni/issues/46,  https://github.com/ess-dmsc/h5cpp/issues/260 and https://github.com/ess-dmsc/h5cpp/issues/282

**Comment by jkotan** [comment]
It was fixed by #66 in the new API
